import { type NetworkLink, type Station, StationIdSchema } from "./domain.ts"

const stationIds = {
  gangnam: StationIdSchema.parse("gangnam"),
  sadang: StationIdSchema.parse("sadang"),
  sindorim: StationIdSchema.parse("sindorim"),
  seoul: StationIdSchema.parse("seoul"),
  hongdae: StationIdSchema.parse("hongdae"),
  jeongbalsan: StationIdSchema.parse("jeongbalsan"),
  daehwa: StationIdSchema.parse("daehwa"),
  suwon: StationIdSchema.parse("suwon"),
  gwangmyeong: StationIdSchema.parse("gwangmyeong"),
  yeongdeungpo: StationIdSchema.parse("yeongdeungpo"),
  yongsan: StationIdSchema.parse("yongsan"),
  jamsil: StationIdSchema.parse("jamsil"),
  konkuk: StationIdSchema.parse("konkuk"),
  wangsimni: StationIdSchema.parse("wangsimni"),
  cheongnyangni: StationIdSchema.parse("cheongnyangni"),
} as const

export const SAMPLE_STATIONS = [
  { id: stationIds.gangnam, name: "강남역", aliases: ["강남"] },
  { id: stationIds.sadang, name: "사당역", aliases: ["사당"] },
  { id: stationIds.sindorim, name: "신도림역", aliases: ["신도림"] },
  { id: stationIds.seoul, name: "서울역", aliases: ["서울"] },
  { id: stationIds.hongdae, name: "홍대입구역", aliases: ["홍대", "홍대입구"] },
  { id: stationIds.jeongbalsan, name: "정발산역", aliases: ["정발산", "일산역", "일산"] },
  { id: stationIds.daehwa, name: "대화역", aliases: ["대화"] },
  { id: stationIds.suwon, name: "수원역", aliases: ["수원"] },
  { id: stationIds.gwangmyeong, name: "광명역", aliases: ["광명"] },
  { id: stationIds.yeongdeungpo, name: "영등포역", aliases: ["영등포"] },
  { id: stationIds.yongsan, name: "용산역", aliases: ["용산"] },
  { id: stationIds.jamsil, name: "잠실역", aliases: ["잠실"] },
  { id: stationIds.konkuk, name: "건대입구역", aliases: ["건대", "건대입구"] },
  { id: stationIds.wangsimni, name: "왕십리역", aliases: ["왕십리"] },
  { id: stationIds.cheongnyangni, name: "청량리역", aliases: ["청량리"] },
] as const satisfies readonly Station[]

export const SAMPLE_NETWORK_LINKS = [
  { from: stationIds.gangnam, to: stationIds.sadang, minutes: 11 },
  { from: stationIds.gangnam, to: stationIds.jamsil, minutes: 14 },
  { from: stationIds.sadang, to: stationIds.sindorim, minutes: 20 },
  { from: stationIds.sadang, to: stationIds.seoul, minutes: 15 },
  { from: stationIds.sadang, to: stationIds.suwon, minutes: 35 },
  { from: stationIds.sindorim, to: stationIds.hongdae, minutes: 12 },
  { from: stationIds.sindorim, to: stationIds.yeongdeungpo, minutes: 3 },
  { from: stationIds.seoul, to: stationIds.hongdae, minutes: 7 },
  { from: stationIds.seoul, to: stationIds.yongsan, minutes: 5 },
  { from: stationIds.seoul, to: stationIds.wangsimni, minutes: 15 },
  { from: stationIds.hongdae, to: stationIds.jeongbalsan, minutes: 25 },
  { from: stationIds.jeongbalsan, to: stationIds.daehwa, minutes: 5 },
  { from: stationIds.suwon, to: stationIds.gwangmyeong, minutes: 20 },
  { from: stationIds.gwangmyeong, to: stationIds.yeongdeungpo, minutes: 18 },
  { from: stationIds.yeongdeungpo, to: stationIds.yongsan, minutes: 10 },
  { from: stationIds.jamsil, to: stationIds.konkuk, minutes: 10 },
  { from: stationIds.jamsil, to: stationIds.wangsimni, minutes: 12 },
  { from: stationIds.konkuk, to: stationIds.wangsimni, minutes: 8 },
  { from: stationIds.wangsimni, to: stationIds.cheongnyangni, minutes: 8 },
] as const satisfies readonly NetworkLink[]
